theme: jekyll-theme-midnight
title: Mobile Gaming screen addiction or just fiction
description: By Kyle M and Brandon T
email: "kylem31415@gmail.com"
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
markdown: redcarpet
redcarpet:
  extensions:
    - no_intra_emphasis
    - fenced_code_blocks
    - autolink
    - tables
    - strikethrough
    - superscript
    - with_to_data
